DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS authorities CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    pw VARCHAR(45) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT username_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS authorities (
    id SERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    auth VARCHAR(45) NOT NULL);